// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoundBag.Models;

namespace SoundBag.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SoundBag.Models.Association", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttendeeId");

                    b.Property<int>("FestivalId");

                    b.HasKey("AssociationId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("FestivalId");

                    b.ToTable("associations");
                });

            modelBuilder.Entity("SoundBag.Models.Association2", b =>
                {
                    b.Property<int>("Association2Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FestivalId");

                    b.Property<int>("UserId");

                    b.HasKey("Association2Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("UserId");

                    b.ToTable("association2");
                });

            modelBuilder.Entity("SoundBag.Models.Festival", b =>
                {
                    b.Property<int>("FestivalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("LineupLink");

                    b.Property<int>("OrganizerId");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("State");

                    b.Property<string>("TicketLink");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("ZipCode");

                    b.HasKey("FestivalId");

                    b.ToTable("festivals");
                });

            modelBuilder.Entity("SoundBag.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FestivalId");

                    b.Property<string>("PostContent")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("SoundBag.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Admin");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SoundBag.Models.Association", b =>
                {
                    b.HasOne("SoundBag.Models.User", "Attendee")
                        .WithMany("Events")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoundBag.Models.Festival", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoundBag.Models.Association2", b =>
                {
                    b.HasOne("SoundBag.Models.Festival", "Event")
                        .WithMany("Posts")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoundBag.Models.User", "Attendee")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
